remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Vehicle Classifier
description: This classifier can classify six types of vecicles. 

author:
  name: Niful Islam

