remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Vehicle Classifier
description: This classifier can classify ten types of paintings. 

author:
  name: Niful Islam
